#!/bin/bash

sudo zypper install \
	git autoconf automake meson ninja-build pkg-config \
	gnu_parallel ruby2.6-rubygem-sass sassc optipng \
	libffi-devel gcc rpm-config-SUSE \
	inkscape gnome-version perl-XML-Twig bc \
	gtk3-devel libgdk_pixbuf-2_0-0 glib2-devel glib2 \
	libxml2-devel librsvg2-devel gnome-shell \
	gnome-themes-standard gtk-murrine-engine gtk2-engines \
	google-roboto-fonts noto-sans-fonts noto-mono-fonts

# Note: some operating systems come with the Numix theme pre-installed.
# We will remove it to avoid conflict with our more up-to-date version.
rpm --quiet -qi numix-gtk-theme && sudo zypper rm numix-gtk-theme
